default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: gadget_master

test:
  <<: *default
  database: gadget_master_development

production:
  <<: *default
  database: gadget_master_production
